Gradle build and clean tests
oracle/javavscode pull request #189
Opened 2024-07-03 05:26 UTC by subhash-arabhi

1. Added tests to see how Java workspace compile and clean works on Gradle projects
2. Reorganised the test folder into different suites 
3. Added few utility functions for testing

2024-07-03 07:14 UTC, Achal1607 requested changes
nitpick: There are some linting issues, can you please format the code. Also, after doing this change, can you please squash the commits.

2024-07-04 05:11 UTC, subhash-arabhi commented
> nitpick: There are some linting issues, can you please format the code. Also, after doing this change, can you please squash the commits.

Fixed linting issues and squashed main commits

2024-07-04 17:51 UTC, Achal1607 commented
Tests are failing, can you please delete `package-lock.json` and  run `npm i` again.

2024-07-10 07:24 UTC, Achal1607 approved these changes

2024-07-15 10:50 UTC, merged