Replace axios with Node provided modules
oracle/javavscode pull request #242
Opened 2024-08-19 10:11 UTC by Achal1607

This PR aims to remove the axios module and instead use 'https' package provided by Node itself.

2024-08-20 03:38 UTC, sid-srini requested changes
This PR would be very useful in removing an extra third-party library dependency. 
Please do remove the `axios` imports from *jdkDownloader.ts* and the dependency from *package.json* and *package-lock.json*. Thanks.

2024-08-20 03:38 UTC, sid-srini commented on vscode/src/jdkDownloader.ts
> +          let data = '';
Perhaps you may add the check for the response status code 200 before attempting to read the data. Similar to the actual file download itself in the function `JDKDownloader`.

2024-08-27 05:19 UTC, sid-srini commented on vscode/src/jdkDownloader.ts
> +            return `HTTP Error ${res.statusCode} - ${res.statusMessage}`;
Should it throw an error here with the message string being returned here?
That way the rejection handler could appropriately notify the user.

2024-08-31 11:11 UTC, Achal1607 commented
Closing since changes done in #248

2024-08-31 11:11 UTC, closed without merging