Initial setup of unit tests
oracle/javavscode pull request #311
Opened 2024-10-29 11:44 UTC by Achal1607

This PR introduces an initial setup for unit testing to help validate fixes more quickly, without the need for a full NetBeans environment and VS Code UI runs. This setup includes sample unit tests for `JDKDownloaderView` in `view.ts` and adds few development dependencies for testing and mocking. A few VS Code-related mocks are also included.

### **List of DevDependencies added and Justification:**
  
- **`@istanbuljs/nyc-config-typescript`:**  
  A code coverage tool, with TypeScript support, ensuring code coverage reporting for TypeScript code.

- **`@types/chai` & `chai`:**  
  `chai` is a popular assertion library used for writing readable and expressive test assertions. `@types/chai` provides TypeScript definitions for `chai`.

- **`@types/sinon` & `sinon`:**  
  `sinon` is a  library for creating mocks, spies, and stubs, useful for isolating and testing code components. `@types/sinon` provides TypeScript definitions.

- **`ts-mockito`:**  
  Provides a simpler API for creating mocks in TypeScript, offering an alternative to `sinon` for creating clean, readable mocks in TypeScript. Sinon doesn't have support for mocking interfaces and namesapce. So, it is also required.

- **`vscode-uri`:**  
  Used for handling and manipulating URIs in a way consistent with VS Code’s own URI utilities, especially useful for file and path manipulations within tests.

2024-10-29 18:08 UTC, sid-srini requested changes
Thanks a lot @Achal1607 for getting the unit tests framework added.

Please do rebase against main after merging #310. 
- That should remove many of the files/changes from the scope of this PR.
- Some work maybe needed to incorporate the changes on newly added tests on *main* like the localisation tests.

Most of my comments are queries for clarification, with few minor code suggestions.

Thanks a lot.

2024-11-04 05:15 UTC, Achal1607 commented on patches/add-licences.diff
Yes all these are dev-dependencies, but currently `PrepareBundles` checks for licenses of all the dependencies during `ant build`. For running test targets it doesn't check for the licenses.
So, do you suggest removing check for licenses of dev-dependencies from the `ant build` target?

2024-11-04 05:19 UTC, Achal1607 commented on vscode/src/test/unit/testUtils.ts
> +            return "aarch64";
I didn't get it, can you please explain?

2024-11-04 05:24 UTC, Achal1607 commented on vscode/src/test/integration/constants.ts
Done

2024-11-04 05:28 UTC, Achal1607 commented on vscode/src/test/unit/mocks/vscode/uri.ts
> + *--------------------------------------------------------------------------------------------*/
Done

2024-11-04 05:28 UTC, Achal1607 commented on vscode/src/test/unit/mocks/vscode/charCode.ts
> + *--------------------------------------------------------------------------------------------*/
Done

2024-11-04 05:30 UTC, Achal1607 commented on vscode/package.json
Chai v5 is not compatible with our repository, I tried installing it first but it doesn't allow named exports. Reference: https://github.com/chaijs/chai/issues/1561

2024-11-04 05:34 UTC, Achal1607 commented on vscode/src/test/unit/mocks/vscode/namespaces/window.ts
> +    when(mockedWindow.showWarningMessage(anyString())).thenReturn(Promise.resolve(undefined));
Done

2024-11-04 09:46 UTC, sid-srini commented on patches/add-licences.diff
Ok. I was only unsure of the origin of where this subset of licenses was coming from.

> So, do you suggest removing check for licenses of dev-dependencies from the `ant build` target?

No, it is fine to keep the check the licenses for dev-dependencies too.
However, we should ensure that the ant task does not include dev-dependency licenses in the the build distribution. I would assume that is out of scope of this PR.

2024-11-04 09:51 UTC, sid-srini commented on vscode/src/test/unit/mocks/vscode/charCode.ts
> + *--------------------------------------------------------------------------------------------*/
Sorry, I'm not able to see any change in this file header in the current commits in the PR.

2024-11-04 09:52 UTC, sid-srini commented on vscode/src/test/unit/mocks/vscode/uri.ts
> + *--------------------------------------------------------------------------------------------*/
Sorry, I'm not able to see any change in this file header in the current commits in the PR.

2024-11-04 09:59 UTC, Achal1607 commented on vscode/src/test/unit/mocks/vscode/uri.ts
> + *--------------------------------------------------------------------------------------------*/
Sorry, I forgot to push that, I had it on my local. I pushed the changes, can you please take a look at it now.

2024-11-04 09:59 UTC, Achal1607 commented on vscode/src/test/unit/mocks/vscode/charCode.ts
> + *--------------------------------------------------------------------------------------------*/
Sorry, I forgot to push that, I had it on my local. I pushed the changes, can you please take a look at it now.

2024-11-04 10:14 UTC, sid-srini commented on vscode/src/test/unit/testUtils.ts
> +            return "aarch64";
With the changes incorporated in #294, the windows OS download would always return the host arch as "x64", even on an "arm64" machine. The test would perhaps fail if "aarch64" is received for this combination.

2024-11-04 10:43 UTC, Achal1607 commented on vscode/src/test/unit/testUtils.ts
> +            return "aarch64";
Done

2024-11-04 10:54 UTC, Achal1607 commented on patches/add-licences.diff
> ++
Done

2024-11-04 10:55 UTC, Achal1607 commented on build.xml
> +            patches/add-licences.diff
Separated  _l10n-licence.diff_ and _dev-dependencies-licenses.diff_. Thanks

2024-11-04 11:25 UTC, sid-srini commented on vscode/package.json
Ok. Thanks.
Should we then use the latest in the previous major version?
- chai: 4.5.0

2024-11-05 05:04 UTC, Achal1607 commented on vscode/package.json
I upgraded it to 4.5.0, it is working fine.

2024-11-05 05:29 UTC, sid-srini approved these changes
Thanks a lot @Achal1607. LGTM 👍

2024-11-05 05:41 UTC, merged