Initial structure of telemetry feature in the extension
oracle/javavscode pull request #342
Opened 2024-12-10 17:28 UTC by Achal1607

Telemetry feature would help us collect extension usage information to improve our extension. Usage info would only be collected if user opts in for the same.

2024-12-12 10:03 UTC, sid-srini reviewed
Thanks a lot @Achal1607.

2024-12-16 09:21 UTC, Achal1607 commented on vscode/src/telemetry/events/baseEvent.ts
> +    protected addEventToCache = (): void => {
Yes your understanding is correct, max would be equal to number of event-types

2024-12-16 12:24 UTC, sid-srini requested changes

2024-12-16 12:24 UTC, sid-srini commented on vscode/src/telemetry/impl/postTelemetry.ts
> +            if (TELEMETRY_API.baseEndpoint == null) {
Perhaps this is supposed to be:
```suggestion
            if (TELEMETRY_API.baseUrl == null) {
```

2024-12-16 12:24 UTC, sid-srini commented on vscode/src/telemetry/telemetry.ts
> +	export const isTelemetryFeatureAvailable = TELEMETRY_API.baseEndpoint != null && TELEMETRY_API.baseEndpoint.trim().length;
Perhaps this is supposed to be:
```suggestion
	export const isTelemetryFeatureAvailable = TELEMETRY_API.baseUrl != null && TELEMETRY_API.baseUrl.trim().length;
```

2024-12-16 17:08 UTC, sid-srini approved these changes
Thanks a lot @Achal1607. LGTM 👍

2024-12-16 17:21 UTC, merged