Adding workflow to build the extension on push and pull request.
oracle/javavscode pull request #39
Opened 2023-10-24 10:29 UTC by lahodaj

2023-10-24 11:49 UTC, sormuras commented on .github/workflows/main.yml
> +        uses: actions/checkout@v3
```suggestion
        uses: actions/checkout@v4
```

Use current version of the checkout action.

2023-10-24 11:50 UTC, sormuras commented on .github/workflows/main.yml
> +        uses: actions/checkout@v3
```suggestion
        uses: actions/checkout@v4
```

Use current version of the checkout action here too.

2023-10-24 11:50 UTC, sormuras requested changes
Use current version, `@v4` as of today, of the checkout action.

2023-10-24 13:12 UTC, lahodaj commented
> Use current version, `@v4` as of today, of the checkout action.

Thanks, applied!

2023-10-24 14:21 UTC, sormuras approved these changes
Workflow steps look good to me.

2023-10-25 06:57 UTC, arvindaprameya approved these changes

2023-10-25 06:57 UTC, merged